spring:
  datasource:
    url: jdbc:h2:mem:clause;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true

clause:
  cors:
    allowed-origins: "*"

logging:
  level:
    com.clause: DEBUG
    org.springframework.web: DEBUG

